import { NextResponse } from 'next/server'

// GET /api/sources - list of integrated literature repositories (RRI-style)
export async function GET() {
  const sources = [
    {
      id: 'semantic_scholar',
      name: 'Semantic Scholar',
      nameZh: 'Semantic Scholar',
      description: 'AI-powered academic search engine; strong CS/bio/physics coverage with citation graphs.',
      descriptionZh: 'AI 驱动的学术搜索引擎；在计算机、生物、物理领域覆盖面广，含引文图谱。',
      url: 'https://www.semanticscholar.org',
      apiDocs: 'https://api.semanticscholar.org',
      free: true,
      needsKey: false,
      rateLimit: '~1 req/sec (free tier)',
      coverage: '~200M papers',
      available: true,
    },
    {
      id: 'crossref',
      name: 'Crossref',
      nameZh: 'Crossref',
      description: 'DOI registry with comprehensive metadata for 150M+ works across all disciplines.',
      descriptionZh: 'DOI 注册机构，覆盖 1.5 亿+条作品元数据，跨学科。',
      url: 'https://www.crossref.org',
      apiDocs: 'https://api.crossref.org',
      free: true,
      needsKey: false,
      rateLimit: '~50 req/sec (polite pool)',
      coverage: '150M+ DOIs',
      available: true,
    },
    {
      id: 'openalex',
      name: 'OpenAlex',
      nameZh: 'OpenAlex',
      description: 'Fully-open catalog of 250M+ works; replaces Microsoft Academic. Rich OA metadata + concepts.',
      descriptionZh: '完全开放的 2.5 亿+作品目录，微软学术的继任者，含丰富的开放获取与概念元数据。',
      url: 'https://openalex.org',
      apiDocs: 'https://docs.openalex.org',
      free: true,
      needsKey: false,
      rateLimit: '~10 req/sec (polite)',
      coverage: '250M+ works',
      available: true,
    },
    {
      id: 'arxiv',
      name: 'arXiv',
      nameZh: 'arXiv',
      description: 'Preprint server for physics, materials, CS, math. Strong for early-stage perovskite/device work.',
      descriptionZh: '物理、材料、计算机、数学预印本服务器，适合追踪钙钛矿等前沿早期工作。',
      url: 'https://arxiv.org',
      apiDocs: 'https://info.arxiv.org/help/api/index.html',
      free: true,
      needsKey: false,
      rateLimit: '~1 req/3sec',
      coverage: '2.4M+ preprints',
      available: true,
    },
    {
      id: 'europepmc',
      name: 'Europe PMC',
      nameZh: 'Europe PMC',
      description: 'Open biomedical & chemistry repository; full-text search across PubMed Central + partners.',
      descriptionZh: '开放生物医学与化学仓储，支持对 PubMed Central 及合作方的全文检索。',
      url: 'https://europepmc.org',
      apiDocs: 'https://europepmc.org/RestfulWebService',
      free: true,
      needsKey: false,
      rateLimit: '~2 req/sec',
      coverage: '40M+ records',
      available: true,
    },
    {
      id: 'unpaywall',
      name: 'Unpaywall',
      nameZh: 'Unpaywall',
      description: 'OA-PDF locator by DOI. Enriches existing papers with legal full-text PDF links (not a search source).',
      descriptionZh: '按 DOI 查找开放获取 PDF 的服务，用于为已有论文补充合法全文 PDF 链接（非检索源）。',
      url: 'https://unpaywall.org',
      apiDocs: 'https://unpaywall.org/products/api',
      free: true,
      needsKey: false,
      rateLimit: '100k/day',
      coverage: 'OA status for 30M+ DOIs',
      available: true,
      isEnricher: true,
    },
    {
      id: 'nrel',
      name: 'NREL Best Research-Cell Efficiency Chart',
      nameZh: 'NREL 最高研究电池效率表',
      description: 'Official certified solar-cell efficiency benchmark (used in the Efficiency tab, not paper search).',
      descriptionZh: '官方认证的太阳能电池效率基准（用于效率标签页，非论文检索）。',
      url: 'https://www.nrel.gov/pv/cell-efficiency.html',
      apiDocs: 'https://www.nrel.gov/pv/assets/pdfs/best-research-cell-efficiencies.pdf',
      free: true,
      needsKey: false,
      rateLimit: 'n/a (manual download)',
      coverage: 'Certified records since 1976',
      available: true,
      isExternal: true,
    },
    {
      id: 'perovskite_db',
      name: 'Perovskite Database',
      nameZh: '钙钛矿数据库',
      description: 'Community-curated perovskite device dataset (efficiency + device params).',
      descriptionZh: '社区维护的钙钛矿器件数据集（效率与器件参数）。',
      url: 'https://perovskitedatabase.com',
      apiDocs: 'https://perovskitedatabase.com/data',
      free: true,
      needsKey: false,
      rateLimit: 'n/a (web query)',
      coverage: '40k+ perovskite devices',
      available: true,
      isExternal: true,
    },
  ]
  return NextResponse.json({ sources })
}
